# Generated by Django 3.2.8 on 2022-10-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название новости')),
                ('preamble', models.CharField(max_length=1024, verbose_name='Описание новости')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Тело новости')),
                ('body_as_markdown', models.BooleanField(default=False, verbose_name='As markdown')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания новостей')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения новости')),
                ('deleted', models.BooleanField(default=False, verbose_name='Новость удалена')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
